### ISSUE TITLE
Sandbox ready for use in production environment?

### ISSUE THREAD

**Issue by garlicgambit** [cloudflare/sandbox#11]
Nice tool.  
  
Is it ready for use in a production environment? Or is it still in testing phase?

**Comment by ignatk** [comment]
We use it for some production services across >200 datacentres. In other words it is a wide deployment of a small set of services. We're in the process of onboarding more services to it.

**Comment by garlicgambit** [comment]
Thanks for the response.  
  
Have a few more questions. Will open separate issues for them.
