### ISSUE TITLE
Cannot build on Arch Linux

### ISSUE THREAD

**Issue by glitsj16** [cloudflare/sandbox#3]
Hi, this looks like a great sandboxing tool. I wanted to build it on Arch Linux but make errors out. Is there anything I can do to fix this?

```
$ git clone https://github.com/cloudflare/sandbox.git
$ cd sandbox
$ make
cc -c -fPIC -Ilibseccomp/include -o sandbox.o sandbox.c
cc -c -fPIC -Ilibseccomp/include -o preload.o preload.c
cc: error: libseccomp/src/.libs/libseccomp.a: No such file or directory
make: *** [Makefile:12: libsandbox.so] Error 1
```

$ pacman -Q gcc libseccomp
gcc 10.1.0-2
libseccomp 2.4.2-1

**Comment by ignatk** [comment]
We recommend compiling `libseccomp` on your own (statically) in a subdir `libseccomp`. I realise these instructions were missed when we migrated the code to GitHub. Will update the README with instructions.

**Comment by ignatk** [comment]
Added instructions to the README
