### ISSUE TITLE
Potential naming conflict with gentoo package of the same name

### ISSUE THREAD

**Issue by glitsj16** [cloudflare/sandbox#5]
Hi, while preparing a PKGBUILD for this project to put in the AUR I noticed that there is already one called [sandbox](https://aur.archlinux.org/packages/sandbox/). It refers to a Gentoo package: https://packages.gentoo.org/packages/sys-apps/sandbox. Unfortunately that one also contains `libsandbox.so`, which _could_ present problems for package management.

I'm not at all experienced with these kind of naming conflicts, nor with any potential legalistics. Just thought it could be helpful to be aware of this.

Regards

**Comment by ignatk** [comment]
Thank you for the information. I would assume `sandbox` is a generic enough word for many solutions, so these conflicts should be resolved at distro level depending on which packages are being used.

I'm not sure we have to take any action here for now, so will close the issue.
