### ISSUE TITLE
PTRACE_O_SUSPEND_SECCOMP requires SYS_ADMIN

### ISSUE THREAD

**Issue by Roguelazer** [cloudflare/sandbox#9]
Trying to figure out why `sandboxify` doesn't work with `failed to suspend seccomp filters for the child: Invalid argument` and realized what the man page says:

> Setting this option requires that the tracer have the CAP_SYS_ADMIN capability, not have any seccomp protections installed, and not have PTRACE_O_SUSPEND_SECCOMP set on itself

Is it expected that `sandboxify` would only work with CAP_SYS_ADMIN? Is there a knob I'm missing somewhere that allows unprivileged users to use `PTRACE_O_SUSPEND_SECCOMP`?

**Comment by ignatk** [comment]
Yes, `sandboxify` currently requires `CAP_SYS_ADMIN` and depending on the target system Linux Yama configuration may also require `CAP_SYS_PTRACE`

**Comment by ignatk** [comment]
Added some information to the `README`
